Генерация float

In [6]:
import numpy as np
np.random.rand()

0.25014280504765707

In [7]:
np.random.rand() * 100

47.50982635723927

In [8]:
np.random.rand(5)

array([0.89181925, 0.74179336, 0.31685436, 0.13786111, 0.3062569 ])

In [9]:
np.random.rand(2, 3)

array([[0.63811423, 0.32274406, 0.11526714],
       [0.19932229, 0.04670764, 0.60977588]])

In [10]:
np.random.rand(2, 3, 4, 10, 12, 23)

array([[[[[[1.80652575e-01, 6.88463032e-01, 2.30102944e-01, ...,
            6.29654359e-01, 8.21176913e-01, 6.87294524e-01],
           [6.77467516e-01, 1.88281730e-01, 7.47160608e-01, ...,
            7.55082320e-02, 4.72591899e-01, 9.93068896e-01],
           [1.03704996e-01, 2.03761112e-01, 6.33032353e-01, ...,
            3.84526946e-01, 3.55658355e-02, 5.78315060e-01],
           ...,
           [7.00920099e-01, 3.42813715e-01, 7.81689911e-01, ...,
            4.34410967e-01, 7.03264951e-01, 1.61484416e-01],
           [6.20575489e-01, 2.26930093e-01, 6.83887810e-01, ...,
            3.87453013e-01, 9.72118016e-01, 8.21988880e-01],
           [1.68135462e-01, 8.34430356e-01, 7.15850537e-01, ...,
            4.69024990e-01, 2.58247465e-01, 2.91262808e-01]],

          [[5.49962688e-01, 6.60295095e-01, 7.79495319e-02, ...,
            9.42522439e-01, 1.91469550e-01, 4.75773254e-01],
           [6.26481738e-02, 8.21892116e-01, 5.50899757e-01, ...,
            8.74158063e-01, 2.22268

shape = (3, 4)
np.random.rand(shape)
# TypeError: 'tuple' object cannot be interpreted as an integer
# Ошибка типов: кортеж не может быть интерпретирован как целое число.

In [11]:
shape = (3, 4)
np.random.rand(*shape)

array([[0.92785938, 0.57494411, 0.21498462, 0.13200787],
       [0.89327918, 0.112277  , 0.32947656, 0.07689951],
       [0.2301505 , 0.60196277, 0.22004168, 0.47376643]])

In [12]:
shape = (2, 3)
np.random.sample(shape)
# array([[0.39756103, 0.01995168, 0.2768951 ],
#       [0.82195372, 0.26435273, 0.00957881]])

array([[0.80683321, 0.75684059, 0.13403139],
       [0.59217751, 0.52071917, 0.46900163]])

uniform(low=0.0, high=1.0, size=None)

In [13]:
np.random.uniform()

0.2236957367974457

In [14]:
np.random.uniform(-30, 50)

23.454688153143344

In [15]:
np.random.uniform(0.5, 0.75, size=5)

array([0.61457141, 0.70698606, 0.60181122, 0.67580529, 0.74563492])

In [16]:
np.random.uniform(-1000, 500, size=(2, 3))

array([[ 465.50490518,  224.01526094,   43.67431341],
       [-980.36967217, -597.94806794,   44.58509907]])

Генерация int

randint(low, high=None, size=None, dtype=int)

In [17]:
np.random.randint(4, size=(2,3))

array([[1, 1, 1],
       [0, 2, 2]], dtype=int32)

In [18]:
np.random.randint(6, 12, size=(3,3))

array([[10,  8,  7],
       [ 8,  7, 11],
       [10,  7,  8]], dtype=int32)

Генерация выборок

In [19]:
#Функция random.shuffle перемешивает тот массив, к которому применяется, и возвращает None.

arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr))
# None
arr
# array([0, 5, 1, 3, 2, 4])

[0 1 2 3 4 5]
None


array([4, 3, 0, 2, 5, 1])

Чтобы получить новый перемешанный массив, а исходный оставить без изменений, можно использовать функцию random.permutation. Она принимает на вход один аргумент — или массив целиком, или одно число:

In [20]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']
print(playlist)
# ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']

['Deep Purple' 'Pink Floyd' 'The Beatles' 'ACDC']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [21]:
np.random.permutation(10)

array([5, 6, 3, 7, 8, 9, 1, 2, 0, 4], dtype=int32)

Чтобы получить случайный набор объектов из массива, используется функция random.choice:

choice(a, size=None, replace=True)

In [22]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['Maria' 'John']


workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=10, replace=False)
print(choice)
# ValueError: Cannot take a larger sample than population when 'replace=False'
# Ошибка значения: нельзя получить выборку больше, чем популяция (популяция — весь доступный набор объектов, из которого получаем выборку), если replace=False (то есть выборка без повторений).

In [32]:
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)

[4 1 5 2 2 4 3 5 5 5]


Seed генератора псевдослучайных чисел

In [ ]:
np.random.seed(23)
np.random.randint(10, size=(3,4))
# array([[3, 6, 8, 9],
#        [6, 8, 7, 9],
#        [3, 6, 1, 2]])

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]], dtype=int32)

In [ ]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

[8 8 3]
[7 7 0]
[4 2 5]
